#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin_MuPDF.Resource", IsApplication=true)]

namespace Xamarin_MuPDF
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f040000
			public const int info = 2130968576;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int busy_indicator = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int button_normal = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int button_pressed = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int canvas = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int page_indicator = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int seek_progress = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int seek_thumb = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int text_border_focused = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int text_border_normal = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int text_border_pressed = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int text_normal = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int text_pressed = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int toolbar = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int busy = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int darkdenim3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_annot = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_annotation = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_arrow_left = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_arrow_right = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_arrow_up = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_cancel = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_check = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_clipboard = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_dir = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_doc = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_highlight = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_link = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_list = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_magnifying_glass = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_more = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_pen = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_print = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_reflow = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_select = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_share = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_strike = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_trash = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_underline = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_updir = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Icon = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int page_num = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int search = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int seek_progress = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int seek_thumb = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int tiled_background = 2130837536;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080024
			public const int MyButton = 2131230756;
			
			// aapt resource value: 0x7f08001f
			public const int acceptButton = 2131230751;
			
			// aapt resource value: 0x7f08001e
			public const int annotType = 2131230750;
			
			// aapt resource value: 0x7f08001d
			public const int cancelAcceptButton = 2131230749;
			
			// aapt resource value: 0x7f08000e
			public const int cancelAnnotButton = 2131230734;
			
			// aapt resource value: 0x7f080014
			public const int cancelDeleteButton = 2131230740;
			
			// aapt resource value: 0x7f080018
			public const int cancelMoreButton = 2131230744;
			
			// aapt resource value: 0x7f080009
			public const int cancelSearch = 2131230729;
			
			// aapt resource value: 0x7f08001a
			public const int copyTextButton = 2131230746;
			
			// aapt resource value: 0x7f080016
			public const int deleteButton = 2131230742;
			
			// aapt resource value: 0x7f080015
			public const int deleteLabel = 2131230741;
			
			// aapt resource value: 0x7f080002
			public const int docNameText = 2131230722;
			
			// aapt resource value: 0x7f08001b
			public const int editAnnotButton = 2131230747;
			
			// aapt resource value: 0x7f08000f
			public const int highlightButton = 2131230735;
			
			// aapt resource value: 0x7f080027
			public const int icon = 2131230759;
			
			// aapt resource value: 0x7f080023
			public const int info = 2131230755;
			
			// aapt resource value: 0x7f080012
			public const int inkButton = 2131230738;
			
			// aapt resource value: 0x7f080003
			public const int linkButton = 2131230723;
			
			// aapt resource value: 0x7f080020
			public const int lowerButtons = 2131230752;
			
			// aapt resource value: 0x7f080007
			public const int moreButton = 2131230727;
			
			// aapt resource value: 0x7f080028
			public const int name = 2131230760;
			
			// aapt resource value: 0x7f080005
			public const int outlineButton = 2131230725;
			
			// aapt resource value: 0x7f080026
			public const int page = 2131230758;
			
			// aapt resource value: 0x7f080022
			public const int pageNumber = 2131230754;
			
			// aapt resource value: 0x7f080021
			public const int pageSlider = 2131230753;
			
			// aapt resource value: 0x7f080019
			public const int printButton = 2131230745;
			
			// aapt resource value: 0x7f080004
			public const int reflowButton = 2131230724;
			
			// aapt resource value: 0x7f08000b
			public const int searchBack = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int searchButton = 2131230726;
			
			// aapt resource value: 0x7f08000c
			public const int searchForward = 2131230732;
			
			// aapt resource value: 0x7f08000a
			public const int searchText = 2131230730;
			
			// aapt resource value: 0x7f080011
			public const int strikeOutButton = 2131230737;
			
			// aapt resource value: 0x7f080000
			public const int switcher = 2131230720;
			
			// aapt resource value: 0x7f080025
			public const int title = 2131230757;
			
			// aapt resource value: 0x7f080001
			public const int topBar0Main = 2131230721;
			
			// aapt resource value: 0x7f080008
			public const int topBar1Search = 2131230728;
			
			// aapt resource value: 0x7f08000d
			public const int topBar2Annot = 2131230733;
			
			// aapt resource value: 0x7f080013
			public const int topBar3Delete = 2131230739;
			
			// aapt resource value: 0x7f080017
			public const int topBar4More = 2131230743;
			
			// aapt resource value: 0x7f08001c
			public const int topBar5Accept = 2131230748;
			
			// aapt resource value: 0x7f080010
			public const int underlineButton = 2131230736;
			
			// aapt resource value: 0x7f080029
			public const int webview = 2131230761;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int buttons = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int outline_entry = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int picker_entry = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int print_dialog = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int textentry = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060036
			public const int ApplicationName = 2131099702;
			
			// aapt resource value: 0x7f060035
			public const int Hello = 2131099701;
			
			// aapt resource value: 0x7f060031
			public const int accept = 2131099697;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int cancel = 2131099652;
			
			// aapt resource value: 0x7f06002a
			public const int cannot_open_buffer = 2131099690;
			
			// aapt resource value: 0x7f060027
			public const int cannot_open_document = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int cannot_open_document_Reason = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int cannot_open_file_Path = 2131099689;
			
			// aapt resource value: 0x7f06002d
			public const int choose_value = 2131099693;
			
			// aapt resource value: 0x7f060022
			public const int copied_to_clipboard = 2131099682;
			
			// aapt resource value: 0x7f060011
			public const int copy = 2131099665;
			
			// aapt resource value: 0x7f060032
			public const int copy_text = 2131099698;
			
			// aapt resource value: 0x7f06002f
			public const int copy_text_to_the_clipboard = 2131099695;
			
			// aapt resource value: 0x7f060013
			public const int delete = 2131099667;
			
			// aapt resource value: 0x7f06001a
			public const int dismiss = 2131099674;
			
			// aapt resource value: 0x7f060026
			public const int document_has_changes_save_them_ = 2131099686;
			
			// aapt resource value: 0x7f060024
			public const int draw_annotation = 2131099684;
			
			// aapt resource value: 0x7f060016
			public const int edit_annotations = 2131099670;
			
			// aapt resource value: 0x7f06000a
			public const int enter_password = 2131099658;
			
			// aapt resource value: 0x7f06001e
			public const int entering_reflow_mode = 2131099678;
			
			// aapt resource value: 0x7f06002b
			public const int fill_out_text_field = 2131099691;
			
			// aapt resource value: 0x7f060033
			public const int format_currently_not_supported = 2131099699;
			
			// aapt resource value: 0x7f060014
			public const int highlight = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int ink = 2131099671;
			
			// aapt resource value: 0x7f06001f
			public const int leaving_reflow_mode = 2131099679;
			
			// aapt resource value: 0x7f060030
			public const int more = 2131099696;
			
			// aapt resource value: 0x7f06001d
			public const int no = 2131099677;
			
			// aapt resource value: 0x7f06000e
			public const int no_further_occurrences_found = 2131099662;
			
			// aapt resource value: 0x7f060003
			public const int no_media_hint = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int no_media_warning = 2131099650;
			
			// aapt resource value: 0x7f060023
			public const int no_text_selected = 2131099683;
			
			// aapt resource value: 0x7f06002e
			public const int not_supported = 2131099694;
			
			// aapt resource value: 0x7f060025
			public const int nothing_to_save = 2131099685;
			
			// aapt resource value: 0x7f06002c
			public const int okay = 2131099692;
			
			// aapt resource value: 0x7f060009
			public const int outline_title = 2131099657;
			
			// aapt resource value: 0x7f06001b
			public const int parent_directory = 2131099675;
			
			// aapt resource value: 0x7f060008
			public const int picker_title_App_Ver_Dir = 2131099656;
			
			// aapt resource value: 0x7f060019
			public const int print = 2131099673;
			
			// aapt resource value: 0x7f060020
			public const int print_failed = 2131099680;
			
			// aapt resource value: 0x7f060018
			public const int save = 2131099672;
			
			// aapt resource value: 0x7f060010
			public const int search = 2131099664;
			
			// aapt resource value: 0x7f060005
			public const int search_backwards = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int search_document = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int search_forwards = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int searching_ = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int select = 2131099663;
			
			// aapt resource value: 0x7f060021
			public const int select_text = 2131099681;
			
			// aapt resource value: 0x7f060012
			public const int strike_out = 2131099666;
			
			// aapt resource value: 0x7f06000b
			public const int text_not_found = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int toggle_links = 2131099661;
			
			// aapt resource value: 0x7f060034
			public const int toggle_reflow_mode = 2131099700;
			
			// aapt resource value: 0x7f060015
			public const int underline = 2131099669;
			
			// aapt resource value: 0x7f060001
			public const int version = 2131099649;
			
			// aapt resource value: 0x7f06001c
			public const int yes = 2131099676;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
